version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spoketa-client
    hostname: spoketa-client
    restart: always
    env_file: .env
    environment:
      - APP_API=$APP_API
    ports:
      - "3003:3003"
    networks:
      - spoketaClient

networks:
  spoketaClient:
